version: "3"

services:
  jupyter-notebooks:
    build:
      context: .
    ports:
      - "8888:8888"
    image: local-dev
    volumes:
      - ./jupyter/notebooks:/home/jovyan/notebooks

    tty: true
